#!/usr/bin/env node
import { mkdir, rm, stat, writeFile } from "node:fs/promises"
import { createRequire } from "node:module"
import { join, resolve } from "node:path"

const options = Object.fromEntries(process.argv.slice(2).reduce((pairs, value, index, values) => value.startsWith("--") ? [...pairs, [value.slice(2), values[index + 1]]] : pairs, []))
const require = createRequire(process.env.PLAYWRIGHT_REQUIRE_FROM ?? import.meta.url)
const { chromium } = require("playwright")
const output = resolve(options.output)
const captures = join(output, "captures")
const result = { runAt: new Date().toISOString(), base: options.base, captures: [], checks: [], consoleErrors: [], failedRequests: [], requests: [], scrollStabilization: [] }
const routes = [["Projekte", "projekte"], ["Workflow", "workflow"], ["Aufgaben", "aufgaben"], ["Artefakte", "artefakte"], ["Pruefungen und Freigaben", "pruefungen-und-freigaben"], ["Uebergabe und Export", "uebergabe-und-export"]]
const viewports = [[1280, 900], [768, 1024], [390, 844], [375, 812]]
const check = (value, name) => { if (!value) throw new Error(name); result.checks.push(name) }
const shot = async (page, file, fullPage = false, element = null) => { const path = join(captures, file); if (element === null) await page.screenshot({ path, fullPage }); else await element.screenshot({ path }); result.captures.push({ file: `captures/${file}`, fullPage, viewport: page.viewportSize(), bytes: (await stat(path)).size }) }
const scrollState = async (page, label) => { const value = await page.locator(".workspace-frame").evaluate(async (element) => { await new Promise((resolveFrame) => requestAnimationFrame(() => resolveFrame())); return { scrollTop: element.scrollTop, overflowAnchor: getComputedStyle(element).overflowAnchor } }); result.scrollStabilization.push({ label, ...value }); check(value.scrollTop === 0, `${label}: scrollTop is zero after requestAnimationFrame`); return value }
const go = async (page, name) => { await page.getByRole("link", { name, exact: true }).click(); const synchronous = await page.locator(".workspace-frame").evaluate((element) => element.scrollTop); result.scrollStabilization.push({ label: `${name} route synchronous`, scrollTop: synchronous }); check(synchronous === 0, `${name}: route scrollTop is zero synchronously`); const state = await scrollState(page, `${name} route`); await page.waitForTimeout(250); check(await page.locator(".workspace-frame").evaluate((element) => element.scrollTop === 0), `${name}: route scrollTop remains zero after settled content`); return state }
const review = async (page, value, fields = {}) => {
  await page.getByLabel("Entscheidung waehlen", { exact: true }).selectOption(value)
  for (const [label, text] of Object.entries(fields)) await page.getByLabel(label, { exact: true }).fill(text)
  const previews = { approve: "Freigabe vorbereiten", reject: "Vorschau fuer Ablehnung erstellen", "request-revision": "Vorschau fuer Revision erstellen", "request-input": "Vorschau fuer Eingabe erstellen", escalate: "Vorschau fuer Eskalation erstellen", "request-waiver": "Vorschau fuer Ausnahme erstellen" }
  await page.getByRole("button", { name: previews[value], exact: true }).click()
  const confirm = page.getByRole("button", { name: /bestaetigen/, exact: false }); await confirm.waitFor(); await confirm.click(); await confirm.waitFor({ state: "detached" }); await page.getByText("Kanonischer Stand aktualisiert", { exact: true }).waitFor()
  check(await page.getByLabel("Entscheidung waehlen", { exact: true }).isEnabled(), `${value}: confirm disappeared and selector enabled`)
}

await rm(captures, { recursive: true, force: true }); await mkdir(captures, { recursive: true })
const context = await chromium.launchPersistentContext(resolve(options.profile), { executablePath: options.chrome, headless: true, viewport: { width: 1280, height: 900 } })
const page = await context.newPage()
page.on("console", (message) => { if (message.type() === "error") result.consoleErrors.push(message.text()) })
page.on("requestfailed", (request) => result.failedRequests.push(request.url()))
page.on("response", (response) => result.requests.push({ url: response.url(), status: response.status(), method: response.request().method() }))
try {
  check((await page.request.get(`${options.base}/unexpected-path`)).status() === 404, "strict server rejects unexpected paths")
  await page.goto(options.base, { waitUntil: "networkidle" }); await page.getByRole("heading", { name: "Synthetic Alpha", exact: true }).waitFor()
  check(await page.locator('link[rel="icon"][href="/favicon.svg"]').count() === 1, "favicon delivery is configured")
  await go(page, "Workflow"); const start = page.getByRole("button", { name: "Naechsten Schritt vorbereiten", exact: true }); await shot(page, "state-rest.png", false, start)
  await start.hover(); await shot(page, "state-hover.png", false, start); await start.focus(); await shot(page, "state-focus.png", false, start); const box = await start.boundingBox(); if (box === null) throw new Error("workflow start action has no box"); await page.mouse.move(box.x + box.width / 2, box.y + box.height / 2); await page.mouse.down(); await shot(page, "state-active.png", false, start); await page.mouse.up(); await page.getByRole("button", { name: "Start verbindlich bestaetigen", exact: true }).waitFor(); await page.getByRole("button", { name: "Start verbindlich bestaetigen", exact: true }).click(); await page.getByText("Readback abgeschlossen.", { exact: true }).waitFor(); await page.reload({ waitUntil: "networkidle" }); await go(page, "Workflow")
  const restartedStart = page.getByRole("button", { name: "Naechsten Schritt vorbereiten", exact: true }); await restartedStart.click(); await page.getByRole("button", { name: "Start verbindlich bestaetigen", exact: true }).waitFor(); await shot(page, "state-awaiting-confirmation.png"); await page.getByRole("button", { name: "Start verbindlich bestaetigen", exact: true }).click(); await page.getByText("Readback abgeschlossen.", { exact: true }).waitFor()
  await go(page, "Aufgaben"); const task = page.getByRole("button", { name: "Themenstruktur pruefen", exact: true }); await task.click(); check(await page.locator(".task-detail dd").filter({ hasText: /^Offen$/ }).count() === 1, "task status is canonical open and localized Offen"); await page.setViewportSize({ width: 390, height: 844 }); await task.scrollIntoViewIfNeeded(); await shot(page, "state-task-selected-mobile.png"); await page.getByRole("button", { name: "Kontext einklappen", exact: true }).click(); await shot(page, "state-context-collapsed.png"); await page.getByRole("button", { name: "Kontext ausklappen", exact: true }).click(); await shot(page, "state-context-expanded.png")
  await page.setViewportSize({ width: 1280, height: 900 }); await go(page, "Artefakte"); await page.getByRole("button", { name: /synthetic-themenstruktur/i }).click(); await page.getByLabel("Artefaktinhalt bearbeiten", { exact: true }).fill("# Synthetische Themenstruktur\n\nPruefbarer Inhalt.\nAktualisierung."); await page.getByRole("button", { name: "Als neue Revision speichern", exact: true }).click(); await page.getByText("Revision 18 wurde unveraenderlich gespeichert.", { exact: true }).waitFor(); await page.getByRole("button", { name: "Revisionen vergleichen", exact: true }).click(); await page.getByText("+ Aktualisierung.", { exact: true }).waitFor(); await page.getByRole("button", { name: "Erneut pruefen", exact: true }).click(); await page.getByText("Maschinenpruefung bestanden", { exact: true }).waitFor()
  await go(page, "Pruefungen und Freigaben"); await review(page, "approve"); await review(page, "reject", { Begruendung: "Synthetischer Grund", Anweisungen: "Synthetische Anweisung", "Betroffene Abschnitte": "Abschnitt A", "Unveraenderliche Vorgaben": "Vorgabe A" }); await review(page, "request-revision", { Begruendung: "Synthetischer Grund", Anweisungen: "Synthetische Anweisung", "Betroffene Abschnitte": "Abschnitt A", "Unveraenderliche Vorgaben": "Vorgabe A" }); await review(page, "request-input", { Begruendung: "Synthetischer Grund", Anweisungen: "Synthetische Anweisung" }); await review(page, "escalate", { Begruendung: "Synthetischer Grund", "Mindestens zwei Optionen": "Option A\nOption B", Auswirkungen: "Synthetische Auswirkung" }); await review(page, "request-waiver", { Begruendung: "Synthetischer Grund", "Pruefanweisung fuer Ausnahme": "Synthetische Anweisung" })
  await page.getByRole("button", { name: "Projekt anlegen", exact: true }).click(); await page.getByLabel("Markdown-Briefing", { exact: true }).fill("# Synthetic Intake\n\nProject V2"); await page.getByRole("button", { name: "Vorschau erstellen", exact: true }).click(); await page.getByRole("button", { name: "Intake verbindlich annehmen", exact: true }).click(); await page.getByText("Schritt 0 bereit", { exact: true }).waitFor(); await page.setViewportSize({ width: 390, height: 844 }); await page.locator(".workspace-frame").evaluate((element) => { element.scrollTop = element.scrollHeight }); check(await page.locator(".workspace-frame").evaluate((element) => element.scrollTop > 0), "intake setup produces nonzero workspace scroll"); const intakeScroll = await go(page, "Projekte"); check(intakeScroll.overflowAnchor === "none", "workspace-frame computed overflow-anchor is none at narrow width")
  for (const [name, slug] of routes) for (const [width, height] of viewports) { await page.setViewportSize({ width, height }); await go(page, name); const geometry = await page.evaluate(() => { const frame = document.querySelector(".workspace-frame"); const shell = document.querySelector(".operator-shell"); const header = document.querySelector(".project-header"); const heading = document.querySelector(".workspace-main h2"); const footer = document.querySelector(".route-action-footer"); return frame && shell && header && heading ? { overflow: document.body.scrollWidth > document.body.clientWidth, owner: getComputedStyle(frame).overflowY, height: shell.getBoundingClientRect().height === innerHeight, heading: heading.getBoundingClientRect().top >= header.getBoundingClientRect().bottom, footer: footer === null || (footer.getBoundingClientRect().top >= frame.getBoundingClientRect().bottom - 1 && getComputedStyle(footer).position === "static") } : null }); check(geometry !== null && !geometry.overflow && geometry.owner === "auto" && geometry.height && geometry.heading && geometry.footer, `${slug} ${width}: bounded shell, no document overflow, normal footer`); await shot(page, `footer-${slug}-${width}x${height}.png`) }
  for (const [name, slug] of routes) for (const [width, height] of [[390, 844], [375, 812]]) { await page.setViewportSize({ width, height }); if (name === "Projekte" && width === 375) { check(await page.locator(".workspace-frame").evaluate((element) => element.scrollTop > 0), "Projects workspace remains scrolled before 375 Workflow transition"); await go(page, "Workflow") }; await go(page, name); const reached = await page.locator(".workspace-frame").evaluate((element) => { element.scrollTop = element.scrollHeight; return Math.abs(element.scrollTop + element.clientHeight - element.scrollHeight) < 2 }); check(reached, `${slug} ${width}: context bottom reachable above footer`); await shot(page, `footer-lower-${slug}-${width}x${height}.png`, true) }
  check(result.consoleErrors.length === 0, "no console errors"); check(result.failedRequests.length === 0, "no failed requests")
  await writeFile(join(output, "footer-pass-browser-results.json"), JSON.stringify(result, null, 2) + "\n")
} finally { await context.close() }
