from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path


CANONICAL_RUNTIME_ERROR_CODES = frozenset(
    {
        "ERR_APPROVAL_STALE", "ERR_ARTIFACT_REQUIRED", "ERR_GATE_REQUIRED", "ERR_IDEMPOTENCY_CONFLICT",
        "ERR_CONCURRENT_DELIVERY_CONFLICT", "ERR_CONCURRENT_PARENT_CONFLICT", "ERR_DELIVERY_IDENTITY_CONFLICT", "ERR_RELEASED_ARTIFACT_IMMUTABLE", "ERR_RETRY_EXHAUSTED", "ERR_STALE_REVISION", "ERR_TENANT_ISOLATION", "ERR_TRANSITION_NOT_ALLOWED",
        "ERROR_AGENTSEO_API_KEY_MISSING", "ERROR_AGENTSEO_FETCH_FAILED", "ERROR_AGENTSEO_HTTP",
        "ERROR_AGENTSEO_JOB_ID_MISSING", "ERROR_AGENTSEO_NETWORK", "ERROR_AGENTSEO_RESPONSE_INVALID",
        "ERROR_AGENTSEO_TIMEOUT",
        "ERROR_ARTIFACT_CONTENT_UNSUPPORTED", "ERROR_ARTIFACT_PERSISTENCE", "ERROR_CONFIGURED_GATE_TOOL_UNAVAILABLE", "ERROR_CRAWL_BROKEN_INTERNAL_LINK", "ERROR_CRAWL_CANONICAL_ISSUE", "ERROR_DELIVERY_PERSISTENCE",
        "ERROR_CRAWL_H1_MISSING", "ERROR_CRAWL_H2_MISSING", "ERROR_CRAWL_HREFLANG_ISSUE", "ERROR_CRAWL_INTERNAL_HTML_4XX",
        "ERROR_CRAWL_INTERNAL_LINK_ISSUE", "ERROR_CRAWL_META_MISSING", "ERROR_CRAWL_REDIRECT_ISSUE", "ERROR_CRAWL_RESOURCE_4XX",
        "ERROR_CRAWL_SECURITY_CRITICAL", "ERROR_CRAWL_SECURITY_ISSUE", "ERROR_CRAWL_SERVER_ERROR", "ERROR_CRAWL_STRUCTURED_DATA_ISSUE",
        "ERROR_CRAWL_TITLE_MISSING", "ERROR_CRAWL_WAIVER_ARTIFACT_BINDING_INVALID", "ERROR_CRAWL_WAIVER_DISALLOWED",
        "ERROR_CRAWL_WAIVER_EVIDENCE_HASH_MISMATCH", "ERROR_CRAWL_WAIVER_EVIDENCE_INVALID", "ERROR_CRAWL_WAIVER_INVALID",
        "ERROR_COMPLIANCE_YMYL_EVIDENCE_REQUIRED", "ERROR_DOMAIN_CONTRACT_FILE_MISSING", "ERROR_DOMAIN_CONTRACT_INVALID",
        "ERROR_DOMAIN_CONTRACT_JSON_INVALID", "ERROR_DOMAIN_GEO_MISMATCH", "ERROR_DOMAIN_LOCAL_PRESENCE_UNVERIFIED",
        "ERROR_DOMAIN_LOCAL_SCOPE_MISSING", "ERROR_DOMAIN_LOCALE_REQUIRED", "ERROR_DOMAIN_MARKET_UNKNOWN",
        "ERROR_DOMAIN_PROVIDER_VERIFICATION_MISMATCH", "ERROR_DOMAIN_REFERENCE_UNKNOWN", "ERROR_DOMAIN_SCHEMA_INVALID",
        "ERROR_CONTEXT_SCHEMA_INVALID", "ERROR_CONTEXT_IDENTITY_MISMATCH", "ERROR_CONTEXT_SOURCE_INVALID",
        "ERROR_CONTEXT_PROMPT_BINDING_INVALID", "ERROR_CONTEXT_OUTPUT_CONTRACT_INVALID", "ERROR_CONTEXT_PREDECESSOR_INVALID",
        "ERROR_CONTEXT_REVISION_BINDING_INVALID", "ERROR_CONTEXT_TRUST_POLICY_INVALID", "ERROR_CONTEXT_PACKAGE_HASH_MISMATCH",
        "ERROR_LLM_REQUEST_INVALID", "ERROR_LLM_REQUEST_IDEMPOTENCY_CONFLICT", "ERROR_LLM_RESULT_INVALID",
        "ERROR_TECHNICAL_SESSION_POLICY_DENIED",
        "ERROR_GATE0_RELEASE_INVALID", "ERROR_GATE1_APPROVAL_INVALID",
        "ERROR_GATE_APPLICABILITY_INVALID", "ERROR_GATE_APPLICABILITY_UNDECIDED", "ERROR_INITIAL_ROUTE_STEP_INVALID", "ERROR_JSONLD_VALIDATOR_UNAVAILABLE", "ERROR_JSONSCHEMA_DEPENDENCY_MISSING", "ERROR_JSONSCHEMA_VERSION", "ERROR_STEP0_CROSS_BINDING_INVALID",
        "ERROR_KEYWORD_INPUT_INVALID", "ERROR_LOCATION_MISMATCH", "ERROR_LOCATION_MISSING",
        "ERROR_LOCATION_TABLE_INVALID", "ERROR_LOCATION_TABLE_MISSING", "ERROR_LOCATION_UNKNOWN",
        "ERROR_OPERATOR_ROUTING_DUPLICATE", "ERROR_OPERATOR_ROUTING_INVALID", "ERROR_OPERATOR_ROUTING_MISSING",
        "ERROR_OPERATOR_ROUTING_POLICY_INVALID", "ERROR_OPERATOR_ROUTING_UNKNOWN_CODE", "ERROR_OPERATOR_ROUTING_UNKNOWN_MAPPING", "ERROR_OUTPUT_CONTRACT_INVALID", "ERROR_OUTPUT_SCHEMA_INVALID",
        "ERROR_REQUIRED_QUALITY_GATE_EVIDENCE", "ERROR_REQUIRED_QUALITY_GATE_MISSING", "ERROR_REQUIRED_QUALITY_GATE_RAW_EVIDENCE",
        "ERROR_QUALITY_GATE_BINDING_INVALID", "ERROR_QUALITY_GATE_EVIDENCE_INVALID", "ERROR_QUALITY_GATE_RUN_SCHEMA_INVALID", "ERROR_REGISTRY_INVALID", "ERROR_REQUIRED_QUALITY_GATE_REGISTRY_VERSION", "ERROR_RUNTIME_PROVIDER_BLOCKED", "ERROR_SCREAMING_FROG_BINARY_MISSING", "ERROR_SCREAMING_FROG_CAPABILITY_MISMATCH",
        "ERROR_SCREAMING_FROG_CONFIG_MISSING", "ERROR_SCREAMING_FROG_CRAWL_FAILED", "ERROR_SCREAMING_FROG_CRAWL_TIMEOUT",
        "ERROR_SCREAMING_FROG_EVIDENCE_INVALID", "ERROR_SCREAMING_FROG_EXPORT_NOT_ALLOWED", "ERROR_SCREAMING_FROG_EXPORTS_MISSING",
        "ERROR_SCREAMING_FROG_ID_INVALID", "ERROR_SCREAMING_FROG_LIMIT_INVALID", "ERROR_SCREAMING_FROG_OUTPUT_NOT_EMPTY",
        "ERROR_SCREAMING_FROG_OUTPUT_PATH_INVALID", "ERROR_SCREAMING_FROG_PREFLIGHT_FAILED", "ERROR_SCREAMING_FROG_PREFLIGHT_TIMEOUT",
        "ERROR_SCREAMING_FROG_URL_INVALID", "ERROR_SCREAMING_FROG_URL_LIMIT_REACHED", "ERROR_STEP1_ARTIFACT_HASH_MISMATCH",
         "ERROR_PROVIDER_GATEWAY", "ERROR_STEP1B_ARCHITECTURE_INVALID", "ERROR_STEP1B_CANONICAL_INVALID",
         "ERROR_PREFLIGHT_CANDIDATE_INVALID", "ERROR_PREFLIGHT_CANDIDATE_STATUS_INVALID", "ERROR_PREFLIGHT_PREDECESSOR_RELEASE_INVALID", "ERROR_PREFLIGHT_PROJECT_IDENTITY_INVALID", "ERROR_PREFLIGHT_SOURCE_ARTIFACT_INVALID",
         "ERROR_PREFLIGHT_PREDECESSOR_INVALID", "ERROR_PREFLIGHT_PREDECESSOR_MISSING", "ERROR_PREFLIGHT_PROJECT_INVALID", "ERROR_PREFLIGHT_GATE_INVALID",
        "ERROR_STEP1B_DECISION_COVERAGE_INVALID", "ERROR_STEP1B_INPUT_INVALID", "ERROR_STEP1B_LINK_GRAPH_INVALID",
        "ERROR_STEP1B_URL_CONFLICT", "ERROR_STEP1C_ACCESSIBILITY_INVALID", "ERROR_STEP1C_INPUT_INVALID",
        "ERROR_STEP1C_JSONLD_REFERENCE_INVALID", "ERROR_STEP1C_LINEAGE_INVALID", "ERROR_STEP1C_LOCATION_CLAIM_INVALID",
        "ERROR_STEP1_ARTIFACT_LINKAGE_INVALID", "ERROR_STEP1_CRAWL_EVIDENCE_INVALID", "ERROR_STEP1_DEPLOYMENT_INVALID",
        "ERROR_STEP1_EVIDENCE_REFERENCE_INVALID", "ERROR_STEP1_IDENTITY_MISMATCH", "ERROR_STEP1_INPUT_INVALID",
         "ERROR_STEP1_INVENTORY_INVALID", "ERROR_STEP1_INVENTORY_NOT_CANONICAL", "ERROR_STEP1_QUALITY_GATE_INVALID",
         "ERROR_STEP1_RUN_INVALID", "ERROR_STEP1_SITE_APPLICABILITY_INVALID", "ERROR_STEP1_STORED_ARTIFACT_MISMATCH",
          "ERROR_STEP1_TRANSITION_INVALID", "ERROR_STEP2_PREFLIGHT", "ERROR_STEP3_PREFLIGHT",
           "ERROR_STEP3B_ADJUSTMENT_INVALID", "ERROR_STEP3B_PLAN_IMMUTABILITY_INVALID", "ERROR_STEP3B_SOURCE_PLAN_INVALID", "ERROR_STEP4A_BRIEFING_INVALID",
           "ERROR_STEP4A_CLAIM_LEDGER_INVALID", "ERROR_STEP4A_CLAIM_LINKAGE_INVALID", "ERROR_STEP4A_SERP_BOUNDARY_INVALID",
           "ERROR_STEP4A_YMYL_CLAIM_INVALID", "ERROR_STEP4A_JSONLD_HASH_MISMATCH", "ERROR_STEP4A_JSONLD_INVALID", "ERROR_STEP4B_CONTENT_HASH_MISMATCH", "ERROR_STEP4B_PAGE_INVALID",
            "ERROR_STEP4B_JSONLD_HASH_MISMATCH", "ERROR_STEP4B_JSONLD_INVALID", "ERROR_STEP4B_MARKUP_UNSAFE", "ERROR_STEP4B_SERVICE_AREA_UNSAFE", "ERROR_STEP4B_STAGING_EVIDENCE_INCOMPLETE", "ERROR_STEP4B_STAGING_INVALID",
           "ERROR_STEP4B_PROJECT_MISSING", "ERROR_STEP4B_PROJECT_INVALID", "ERROR_STEP4B_DEPLOYMENT_INVALID", "ERROR_STEP4B_LOCALE_MISMATCH", "ERROR_STEP4B_SERVICE_AREA_UNSUPPORTED", "ERROR_STEP4B_PHYSICAL_LOCATION_INVALID",
           "ERROR_OUTPUT_STEP_UNKNOWN", "ERROR_OUTPUT_IDENTIFIER_INVALID", "ERROR_OUTPUT_ROOT_INVALID", "ERROR_OUTPUT_PATH_ESCAPE", "ERROR_OUTPUT_EXISTS",
           "ERROR_SERP_INPUT_INVALID", "ERROR_STEP_PREFLIGHT_INVALID", "ERROR_TRANSITION_LEDGER_LOCKED", "ERROR_LOCAL_FIXTURE_UNAVAILABLE",
    }
)


@dataclass(frozen=True, slots=True)
class ErrorRoute:
    code: str
    route: str
    owner_type: str


@dataclass(frozen=True, slots=True)
class PolicyValidation:
    valid: bool
    canonical_codes: tuple[str, ...]
    errors: tuple[str, ...]


class ErrorRoutingPolicyError(RuntimeError):
    def __init__(self, code: str, message: str) -> None:
        super().__init__(message)
        self.code = code


def load_policy(root: Path | None = None) -> dict[str, str | list[dict[str, str]]]:
    policy_root = root or Path(__file__).resolve().parents[2]
    return json.loads(
        (policy_root / "standards" / "operator" / "error-routing-policy.json").read_text(encoding="utf-8")
    )


def validate_policy(policy: dict[str, str | list[dict[str, str]]]) -> PolicyValidation:
    mappings = policy.get("mappings")
    if not isinstance(mappings, list):
        return PolicyValidation(False, tuple(sorted(CANONICAL_RUNTIME_ERROR_CODES)), ("ERROR_OPERATOR_ROUTING_INVALID",))
    codes = [mapping.get("code") for mapping in mappings if isinstance(mapping, dict)]
    duplicate = len(codes) != len(set(codes))
    mapped = frozenset(code for code in codes if isinstance(code, str))
    errors: list[str] = []
    if duplicate:
        errors.append("ERROR_OPERATOR_ROUTING_DUPLICATE")
    if mapped.difference(CANONICAL_RUNTIME_ERROR_CODES):
        errors.append("ERROR_OPERATOR_ROUTING_UNKNOWN_MAPPING")
    if CANONICAL_RUNTIME_ERROR_CODES.difference(mapped):
        errors.append("ERROR_OPERATOR_ROUTING_MISSING")
    return PolicyValidation(not errors, tuple(sorted(CANONICAL_RUNTIME_ERROR_CODES)), tuple(errors))


def route_error(code: str, policy: dict[str, str | list[dict[str, str]]]) -> ErrorRoute:
    validation = validate_policy(policy)
    if not validation.valid:
        raise ErrorRoutingPolicyError("ERROR_OPERATOR_ROUTING_POLICY_INVALID", "Runtime error routing policy is incomplete or duplicated.")
    for mapping in policy["mappings"]:
        if mapping["code"] == code:
            return ErrorRoute(code, mapping["route"], mapping["owner_type"])
    raise ErrorRoutingPolicyError("ERROR_OPERATOR_ROUTING_UNKNOWN_CODE", f"No operator route exists for runtime error code {code}.")
