import { releasedArtifactRemediation, useArtifactRevision } from "./useArtifactRevision"
import type { ArtifactRevisionApi, ArtifactRevisionData } from "./useArtifactRevision"

export function ArtifactWorkspace({ api, data }: { readonly api: ArtifactRevisionApi; readonly data: ArtifactRevisionData }): JSX.Element {
  const artifact = data.current.artifact
  const revision = useArtifactRevision({ api, data })
  if (artifact === null) return <section className="work-panel"><h2>Artefakte</h2><p>Kein aktuelles Artefakt vorhanden.</p></section>
  const comparedRevisionIsDistinct = revision.parentArtifact !== null && revision.comparisonArtifact !== null && revision.parentArtifact.artifact_id !== revision.comparisonArtifact.artifact_id
  return <section className="artifact-layout"><section className="work-panel"><h2>Artefakte</h2><label>Ausgangsrevision<select aria-label="Ausgangsrevision" value={revision.parentArtifact?.artifact_id ?? ""} onChange={(event) => revision.setParentArtifactId(event.currentTarget.value)} disabled={revision.isSaving || revision.isReadbackPending}><option value="">Revision waehlen</option>{revision.revisions.map((entry) => <option key={entry.artifact_id} value={entry.artifact_id}>Revision {entry.revision}</option>)}</select></label><button type="button" className="artifact-row" onClick={() => void revision.loadContent()} disabled={!revision.canLoadContent}>{revision.parentArtifact?.storage_key ?? artifact.storage_key}, Revision {revision.parentArtifact?.revision ?? artifact.revision}</button><label>Artefaktinhalt bearbeiten<textarea aria-label="Artefaktinhalt bearbeiten" value={revision.content} onChange={(event) => revision.setContent(event.currentTarget.value)} disabled={revision.isEditingLocked} /></label><label>Neue Revision<select aria-label="Neue Revision" value={revision.comparisonArtifact?.artifact_id ?? ""} onChange={(event) => revision.setNewArtifactId(event.currentTarget.value)} disabled={revision.isSaving || revision.isReadbackPending}><option value="">Neue Revision waehlen</option>{revision.revisions.map((entry) => <option key={entry.artifact_id} value={entry.artifact_id}>Revision {entry.revision}</option>)}</select></label><div aria-label="Artefaktaktionen" className="action-row"><button type="button" onClick={() => void revision.save()} disabled={revision.content === "" || revision.isEditingLocked}>Als neue Revision speichern</button><button type="button" onClick={() => void revision.compare()} disabled={!comparedRevisionIsDistinct || revision.isSaving || revision.isReadbackPending}>Revisionen vergleichen</button><button type="button" onClick={() => void revision.validate()} disabled={revision.newArtifact === null || revision.isSaving || revision.isReadbackPending}>Erneut pruefen</button></div>{revision.isReleased ? <p className="action-blocker">{releasedArtifactRemediation}</p> : null}{revision.isReadbackPending ? <p aria-live="polite">Kanonische Revisionsliste wird geladen.</p> : null}{revision.error === null ? null : <p role="alert" className="action-blocker">{revision.error}</p>}{revision.newArtifact === null ? null : <p className="success-note">Revision {revision.newArtifact.revision} wurde unveraenderlich gespeichert.</p>}{revision.diff === "" ? null : <pre>{revision.diff}</pre>}{revision.validation === "" ? null : <p className="success-note">{revision.validation}</p>}</section><aside className="evidence-inline"><h3>Revisionslinie</h3><p>Neue Inhalte erhalten eine eigene unveraenderliche Revision.</p></aside></section>
}
